# modules/codisto/config/routes.yml
admin_codistohome:
    path: /codisto/home
    methods: [GET]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::homeAction'
      _legacy_controller: AdminCodistoHome

admin_codistolistings:
    path: /codisto/listings/
    methods: [GET]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::listingsAction'
      _legacy_controller: AdminCodistoListings

admin_codistoorders:
    path: /codisto/orders/
    methods: [GET]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::ordersAction'
      _legacy_controller: AdminCodistoOrders

admin_codistosettings:
    path: /codisto/settings/
    methods: [GET]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::settingsAction'
      _legacy_controller: AdminCodistoSettings

admin_codistoaccount:
    path: /codisto/account/
    methods: [GET]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::accountAction'
      _legacy_controller: AdminCodistoAccount

admin_codistoebay_templates:
    path: /codisto/templates
    methods: [GET]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::templateAction'
      _legacy_controller: AdminCodistoEbayTemplates

admin_codisto_create:
    path: /codisto/create
    methods: [GET, POST]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::createAccountAction'
      _legacy_controller: AdminCodistoHome

admin_codisto_update_template:
    path: /codisto/updatetemplate
    methods: [GET, POST]
    defaults:
      _controller: 'PrestaShop\Module\Codisto\Controller\Admin\AdminCodistoHomeController::updateTemplateAccountAction'
      _legacy_controller: AdminCodistoHome
