## \file hypotez/src/product/ttypes.py
# -*- coding: utf-8 -*-
#! venv/Scripts/python.exe # <- venv win
## ~~~~~~~~~~~~~
""" module: src.product """
""" Определение типa `product` """
from typing import TypedDict, Optional

class ProductType(TypedDict, total=False):
    id_product: Optional[int]
    id_supplier: Optional[int]
    id_manufacturer: Optional[int]
    id_category_default: Optional[int]
    id_shop_default: Optional[int]
    id_tax: Optional[int]
    on_sale: Optional[int]
    online_only: Optional[int]
    ean13: Optional[str]
    isbn: Optional[str]
    upc: Optional[str]
    mpn: Optional[str]
    ecotax: Optional[float]
    quantity: Optional[int]
    minimal_quantity: Optional[int]
    low_stock_threshold: Optional[int]
    low_stock_alert: Optional[int]
    price: Optional[float]
    wholesale_price: Optional[float]
    unity: Optional[str]
    unit_price_ratio: Optional[float]
    additional_shipping_cost: Optional[float]
    reference: Optional[str]
    supplier_reference: Optional[str]
    location: Optional[str]
    width: Optional[float]
    height: Optional[float]
    depth: Optional[float]
    weight: Optional[float]
    volume: Optional[str]
    out_of_stock: Optional[int]
    additional_delivery_times: Optional[int]
    quantity_discount: Optional[int]
    customizable: Optional[int]
    uploadable_files: Optional[int]
    text_fields: Optional[int]
    active: Optional[int]
    redirect_type: Optional[str]
    id_type_redirected: Optional[int]
    available_for_order: Optional[int]
    available_date: Optional[str]  # 'date' in SQL corresponds to a string in Python
    show_condition: Optional[int]
    condition: Optional[str]
    show_price: Optional[int]
    indexed: Optional[int]
    visibility: Optional[str]
    cache_is_pack: Optional[int]
    cache_has_attachments: Optional[int]
    is_virtual: Optional[int]
    cache_default_attribute: Optional[int]
    date_add: Optional[str]  # 'datetime' in SQL corresponds to a string in Python
    date_upd: Optional[str]  # 'datetime' in SQL corresponds to a string in Python
    advanced_stock_management: Optional[int]
    pack_stock_type: Optional[int]
    state: Optional[int]
    product_type: Optional[str]
    link_to_video: Optional[str]
